### ISSUE TITLE
Scss之CSS扩展

### ISSUE THREAD

**Issue by Cyclone77** [Cyclone77/Cyclone77-Blog#3]
- [CSS扩展 (CSS Extensions)](#css扩展-css-extensions)
    - [嵌套规则 (Nested Rules)](#嵌套规则-nested-rules)
    - [引用父选择器:& (Referencing Parent Selectors: &)](#引用父选择器-referencing-parent-selectors-)
    - [嵌套属性 (Nested Properties)](#嵌套属性-nested-properties)
    - [占位符选择器](#占位符选择器)
- [注释: /* */ 和 //（Comments: /* */ and //）](#注释---和-comments---and-)

# CSS扩展 (CSS Extensions)

## 嵌套规则 (Nested Rules)

`Scss` 允许将一个CSS样式嵌套到另一个样式中，内层样式仅适用于外层样式选择器的范围之类
``` scss
#main {
    width: 97%;
    p,div {
        font-size: 2em;
        a {
            font-weight: bold;
        }
    }
}
```
编译为：
``` css
#main {
  width: 97%; }
  #main p, #main div {
    font-size: 2em; }
    #main p a, #main div a {
      font-weight: bold; }
```

## 引用父选择器:& (Referencing Parent Selectors: &)

`&` 将替换为呈现在CSS文件中的父选择器，使用相当灵活，可以作用域子选择器（包括伪元素），父选择器；

> 必须出现在的选择器的开头位置，但可以跟随后缀，将被添加到父选择的后面；否则Scss编译报错。

例如：
``` scss
a{
    font-weight: bold;
    text-decoration: none;
    span{
        display: inline-block;
        &-link:em{
            font-size: 12px;
        }
    }
    &:hover{
        text-decoration: underline;
    }
    .firefox &{
        font-weight: normal;
    }
}
```
编译后：
``` css
a {
  font-weight: bold;
  text-decoration: none; }
  a span {
    display: inline-block; }
    a span-link:em {
      font-size: 12px; }
  a:hover {
    text-decoration: underline; }
  .firefox a {
    font-weight: normal; }
```

## 嵌套属性 (Nested Properties)

CSS中有一些属性遵循相同的“命名空间”；比如，font-family, font-size, 和 font-weight都在font命名空间中。
在编写这些属性的时候每次都得写font-*之类的属性。Scss提供了快捷方式`:`（冒号）只需要输入一次命名空间，然后在其内部嵌套子属性。
> 命名空间可以有自己的属性

例如：
``` scss
.funky {
    font: 20px/24px {
        family: fantasy;
        weight: bold;
    }
}
```
编译后：
``` css
.funky {
  font: 20px/24px;
    font-family: fantasy;
    font-weight: bold; }
```

## 占位符选择器

%foo是Sass 支持一种特殊类型的选择器,叫做"占位符选择器" (placeholder selector)。

# 注释: /* */ 和 //（Comments: /* */ and //）

Sass 支持标准的CSS多行注释以/* */以及单行注释 //。在尽可能的情况下，多行注释会被保留在输出的CSS中，而单行注释会被删除。
