### ISSUE TITLE
SCSS变量及运算

### ISSUE THREAD

**Issue by Cyclone77** [Cyclone77/Cyclone77-Blog#4]
- [变量](#变量)
- [数据类型](#数据类型)
    - [字符串（Strings）](#字符串strings)
- [运算](#运算)
    - [数字运算 (Number Operations)](#数字运算-number-operations)
        - [除法和 / （Division and /）](#除法和--division-and-)

# 变量

变量以美元符号开始，赋值像设置CSS属性那样：
``` scss
$width: 5em;
```
可以在属性中引用他们：
``` scss
#main{
    width: $width;
}
```
> 变量分为局部变量和全局变量。定义变量的时候可以在后面带上`!global`的标志这种情况变量在任何地方可见及全局变量。

例如：

``` scss
$width: 5em; //全局变量
#main {
    $height: 5em !global; //带有 !global 的全局变量
    $fontsize: 14px;
    width: $width;
    height: $height;
    font-size: $fontsize;
}

#sidebar {
    width: $width;
    height: $height;
    // font-size: $fontsize; 这里编译提示 $fontsize 找不到
}
```
编译为：
``` css
#main {
  width: 5em;
  height: 5em;
  font-size: 14px; }

#sidebar {
  width: 5em;
  height: 5em; }
```
> 注意：Scss 变量中出现连接符`_`、`-`是可以互换的；也就是说变量名 `$main-width` 和 `$main_width` 是同一个变量。

# 数据类型

SassScript 支持 7 种主要的数据类型：
- 数字 (例如： 1.2, 13, 10px)
- 文本字符串，带引号字符串和不带引号字符串(例如："foo", 'bar', baz)
- 颜色 (例如：blue, #04a3f9, rgba(255, 0, 0, 0.5))
- 布尔值 (例如： true, false)
- 空值 (例如： null)
- 值列表 (list)，用空格或逗号分隔 (例如： 1.5em 1em 0 2em, Helvetica, Arial, sans-serif)
- maps ，从一个值映射到另一个 (例如： (key1: value1, key2: value2))

> !important Scss会当成不带引号的字符串。

## 字符串（Strings）
Css 指定2种字符串带引号的字符串和不带引号的字符串（css关键字），Scss识别这2种字符串。

> 注： 当使用 #{} interpolation 时，带引号的字符串将被编译为不带引号的字符串。

例如： 
``` scss
$content: "这里是自定义内容！";
$bgcolor: #808080; //不带引号的字符串
.footer:after{
    content: "#{$content} 每个after设置的固定内容。";
    background-color: $bgcolor; 
}
```
编译为：
``` css 
.footer:after {
  content: "这里是自定义内容！ 每个after设置的固定内容。";
  background-color: #808080; }
```

# 运算

所有数据类型的支持相等运算(== 和 !=)。此外，每种类型都有其自己特殊的运算方式。

## 数字运算 (Number Operations)

SassScript 支持对数字标准的算术运算（加法+，减法 - ，乘法*，除法/和取模%）。Sass 数学函数在算术运算期间会保留单位。

### 除法和 / （Division and /）

CSS允许 / 出现在属性值之间作为分隔数字的方式(愚人码头注：例如font属性，p.ex2{font:italic bold 12px/20px arial,sans-serif;})。
在SCSS中将`/` 解析为除法的三种情况：

- 如果该值，或值的任何部分，存储在一个变量中或通过函数返回。
- 如果该值是由括号括起来的，除非这些括号是在一个列表（list）外部，并且值是括号内部。
- 如果该值被用作另一个算术表达式的一部分。

> 总结一下：凡是CSS原生支持的写法，则保留，否则SCSS视为运算；括号内的是表达式则参于运算，如果死list则括号被忽略。

例如：
``` scss 
p {
    font: 10px/8px; // 原生的CSS，不作为除法
    $width: 1000px;
    width: $width/2; // 使用了变量, 作为除法
    width: round(1.5)/2; // 使用了函数, 作为除法
    height: (500px/2); // 使用了括号, 作为除法
    margin-left: 5px + 8px/2px; // 使用了 +, 作为除法
    font: (italic bold 10px/8px); // 在一个列表（list）中，括号可以被忽略。
}
```
编译为：
``` css
p {
  font: 10px/8px;
  width: 500px;
  width: 1;
  height: 250px;
  margin-left: 9px;
  font: italic bold 10px/8px; }
```
> 当然如果使用了变量并且想保留`/`不视为运算符，则使用`#{}`来调用变量
