### ISSUE TITLE
SCSS特殊操作

### ISSUE THREAD

**Issue by Cyclone77** [Cyclone77/Cyclone77-Blog#5]
- [函数 (Functions)](#-functions)
- [插值：#{}（Interpolation: #{}）](#interpolation-)
- [SassScript中的&（& in SassScript）](#sassscript-in-sassscript)
- [变量默认: !default （Variable Defaults: !default）](#-default-variable-defaults-default)

# 函数 (Functions)

SCSS 提供大量的函数；请见: [Sass::Script::Functions](http://sass-lang.com/documentation/Sass/Script/Functions.html)

# 插值：#{}（Interpolation: #{}）

可以通过 `#{}` 插值语法在选择器和属性名中使用 SassScript 变量：
``` scss
$name: foo;
$attr: border;
p.#{$name} {
    #{$attr}-color: blue;
}
```
编译为：
``` css
p.foo {
  border-color: blue; }
```
> `#{}`插值语法不如直接使用变来快捷，但是可以避免各种运算，带来的困扰

例如：
``` scss
p {
    $font-size: 12px;
    $line-height: 30px;
    font: #{$font-size}/#{$line-height};
}
```
编译为：
``` css
p {
  font: 12px/30px; }
```

# SassScript中的&（& in SassScript）

就像当它在选择器中使用一样，SassScript中的&指向当前父选择器。
``` scss
.foo.bar .baz.bang, .bip.qux {
    $selector: &;
    #{$selector} .p{
        font-size: 14px;
    }
}
```
$selector的值是现在 ((".foo.bar" ".baz.bang"), ".bip.qux")。

> 如果没有父选择器，&的值将是空。

这意味着你可以在一个`mixin`中使用它来检测父选择是否存在。

# 变量默认: !default （Variable Defaults: !default）

> 设置变量的默认值，如果变量已经赋值，如果赋予新值并且加了`!default`则不会被重新赋值。一般我们把默认变量放着最前面保证变量有初始值。

例如：
``` scss
$content: "First content";
$content: "Second content?" !default;
$new_content: "First time reference" !default;
$new_content: "Second time reference";

#main {
    content: $content;
    new-content: $new_content;
}
```
编译为：
``` css
#main {
  content: "First content";
  new-content: "Second time reference"; }
```
